### ISSUE TITLE
require() of ES Module

### ISSUE THREAD

**Issue by tidusvn05** [squareboat/nest-console#12]
i got new issue when start project.

Nestjs 9

"@squareboat/nest-console": "^1.1.0",

```
node_modules/@squareboat/nest-console/dist/inquirer.js:16
const inquirer_1 = __importDefault(require("inquirer"));
                                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@squareboat/nest-console/node_modules/inquirer/lib/inquirer.js
```

**Comment by tidusvn05** [comment]
*Update: it working on version 1.0.9
maybe that is a problem of new version

**Comment by vinayak25** [comment]
Hello @tidusvn05, due to nestjs not giving out complete support for ESM Module, I have downgraded the inquirer and ora package to their previous commonjs versions. Please feel free to use v1.1.1 from npm.
