### ISSUE TITLE
Deadlink in postinstall.js

### ISSUE THREAD

**Issue by scorsi** [squareboat/nest-console#2]
Hello,

https://github.com/squareboat/nest-console/blob/6e3e11e942637a6e6011a3133d3afa27bf327f69/postinstall.js#L21 contains a dead link to https://squareboat.com/open-source/nest-console/config. 

Thanks,

**Comment by scorsi** [comment]
I already take a look at the source code, the check for the options argument is simply done after the one for required arguments.

**Comment by vinayak25** [comment]
Released in [`v0.0.4`](https://github.com/squareboat/nest-console/releases/tag/v0.0.4)
